---
esphome:
  name: test-nuki

  libraries:
    - Preferences
    - https://github.com/nkolban/ESP32_BLE_Arduino/
    - https://github.com/uriyacovy/NukiBleEsp32

esp32:
  board: "esp32dev"
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0

wifi:
  ssid: "My Network"
  password: "My Password"

api:

external_components:
  - source:
      type: local
      path: "../components/"

lock:
  - platform: nuki_lock
    name: My Nuki Lock
    is_paired:
      name: "Nuki Paired"
    battery_critical:
      name: "Nuki Battery Critical"
    battery_level:
      name: "Nuki Battery Level"
    is_connected:
      name: "Nuki Connected"
    door_sensor:
      name: "Nuki Door Sensor"
    door_sensor_state:
      name: "Nuki Door Sensor State"
