---
  name: Build Component

  on:
    push:
    pull_request:

  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Compile Firmware
          uses: esphome/build-action@v5.0.0
          with:
            yaml-file: .github/test-config.yaml